name: CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn
      # - run: yarn test
      - run: yarn build
        env:
          VITE_APP_S3_BUCKET: ${{ secrets.VITE_APP_S3_BUCKET }}
          VITE_APP_COGNITO_LOGIN_URL: ${{ secrets.VITE_APP_COGNITO_LOGIN_URL }}
          VITE_APP_COGNITO_LOGOUT_URL: ${{ secrets.VITE_APP_COGNITO_LOGOUT_URL }}
          VITE_APP_COGNITO_REGION: ${{secrets.VITE_APP_COGNITO_REGION }}
          VITE_APP_COGNITO_IDENTITY_POOL_ID: ${{ secrets.VITE_APP_COGNITO_IDENTITY_POOL_ID }}
          VITE_APP_COGNITO_IDENTITY_PROVIDER: ${{ secrets.VITE_APP_COGNITO_IDENTITY_PROVIDER }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - run: aws s3 sync ./dist s3://${{ secrets.DOMAIN_URL }}
      # - if: ${{ failure() }}
      #   name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_COLOR: "#FF0000"
      #     SLACK_TITLE: "Build failed"
      # - if: ${{ success() }}
      #   name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_TITLE: "Build success"
